In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import keras

from keras.models import Sequential 
from keras.layers import Dense, Activation, Convolution2D, Reshape, Flatten, MaxPooling2D
from keras.utils import np_utils

Using Theano backend.


In [4]:
ds = pd.read_csv('fer2013.csv')
d = ds.values
d.shape

(35887, 3)

In [5]:
arr = np.array([1,2,3])
b = np.array([4, 5, 6])

arr = np.vstack((arr, b))
c = np.array([7, 8 ,9])
arr = np.vstack((arr, c))
#print arr

x = [1, 2, 3]
y = [4, 5, 6]

p = np.array(x)
print p

print x

[1 2 3]
[1, 2, 3]


In [6]:
labels = d[:, 0]
print labels.shape

tem = d[:, 1]
pixels = np.zeros((d.shape[0], 48*48))
# t = d[0, 1]
# t = t.split()
# t = [ int(z) for z in t ]
# data1 = np.array(t)
# print data1

# for ix in range(1, d.shape[0]):
#     tem = d[ix, 1]
#     tem = tem.split()
#     tem = [ int(z) for z in tem ]
#     data = np.vstack((data, np.array(tem)))

for ix in range(d.shape[0]):
    t = tem[ix].split(' ')
    for iy in range(d.shape[1]):
        pixels[ix, iy] = int(t[iy])


(35887,)


In [7]:
print pixels.shape
    
print pixels[:2, :10]

(35887, 2304)
[[  70.   80.   82.    0.    0.    0.    0.    0.    0.    0.]
 [ 151.  150.  147.    0.    0.    0.    0.    0.    0.    0.]]


In [8]:
y = np_utils.to_categorical(labels)
print y.shape

(35887, 7)


In [9]:
split = int(0.80*pixels.shape[0])

x_train = pixels[:split]
y_train = y[:split]

x_test = pixels[split:]
y_test = y[split:]

print x_train.shape, x_test.shape
print y_train.shape, y_test.shape

(28709, 2304) (7178, 2304)
(28709, 7) (7178, 7)


In [10]:
x_train = x_train.reshape((x_train.shape[0], 1, 48, 48))
x_test = x_test.reshape((x_test.shape[0], 1, 48, 48))

print x_train.shape, x_test.shape
print y_train.shape, y_test.shape

(28709, 1, 48, 48) (7178, 1, 48, 48)
(28709, 7) (7178, 7)


In [22]:
conv_model = Sequential()

conv_model.add(Convolution2D(16, 3, 3, input_shape=(1, 48, 48)))
conv_model.add(Activation('relu'))
conv_model.add(Convolution2D(8, 3, 3))
conv_model.add(Activation('relu'))

conv_model.add(MaxPooling2D(pool_size=(2, 2)))
conv_model.add(Convolution2D(4, 3, 3))
conv_model.add(Activation('relu'))

conv_model.add(Flatten())

conv_model.add(Dense(7))
conv_model.add(Activation('softmax'))

conv_model.summary()
conv_model.compile(loss='categorical_crossentropy', optimizer='adam',
                  metrics=['accuracy'])

____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
convolution2d_20 (Convolution2D) (None, 16, 46, 46)    160         convolution2d_input_5[0][0]      
____________________________________________________________________________________________________
activation_24 (Activation)       (None, 16, 46, 46)    0           convolution2d_20[0][0]           
____________________________________________________________________________________________________
convolution2d_21 (Convolution2D) (None, 8, 44, 44)     1160        activation_24[0][0]              
____________________________________________________________________________________________________
activation_25 (Activation)       (None, 8, 44, 44)     0           convolution2d_21[0][0]           
___________________________________________________________________________________________

In [23]:
hist = conv_model.fit(x_train, y_train,
                     nb_epoch=5,
                     shuffle=True,
                      batch_size=1024,
                     validation_data=(x_test, y_test))

Train on 28709 samples, validate on 7178 samples
Epoch 1/5
28709/28709 [==============================] - 95s - loss: 1.8765 - acc: 0.2153 - val_loss: 1.8174 - val_acc: 0.2471
Epoch 2/5
28709/28709 [==============================] - 95s - loss: 1.8107 - acc: 0.2513 - val_loss: 1.8104 - val_acc: 0.2471
Epoch 3/5
28709/28709 [==============================] - 111s - loss: 1.8059 - acc: 0.2513 - val_loss: 1.8083 - val_acc: 0.2471
Epoch 4/5
28709/28709 [==============================] - 89s - loss: 1.8047 - acc: 0.2521 - val_loss: 1.8054 - val_acc: 0.2471
Epoch 5/5
28709/28709 [==============================] - 93s - loss: 1.7994 - acc: 0.2514 - val_loss: 1.8016 - val_acc: 0.2471
